# Generated by Django 5.2 on 2025-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'seat_number')},
        ),
    ]
